# Generated by Django 5.0.4 on 2024-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_order_customer_orders_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_done',
            field=models.BooleanField(default=False, verbose_name='Подтверждение готовности от заказчика'),
        ),
        migrations.AddField(
            model_name='orders',
            name='performer_done',
            field=models.BooleanField(default=False, verbose_name='Подтверждение готовности от исполнителя'),
        ),
        migrations.AddField(
            model_name='orders',
            name='potential_performers',
            field=models.TextField(blank=True, null=True, verbose_name='IDs потенциальных исполнителей'),
        ),
    ]
