# Generated by Django 5.0.4 on 2024-04-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orders_customer_done_orders_performer_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='potential_performers',
            field=models.TextField(default='[]', verbose_name='IDs потенциальных исполнителей'),
        ),
    ]
